name: nexver

description: |
  Detect current version of a package and calculate the next one.
  Supports monorepo and uses templates for detection of version and output.
  It supports (configurable) conventional commits.

inputs:
  base-ref:
    default: ""
    required: false
    description: Not in use. Keept for backward compatibility.
  head-ref:
    default: ""
    required: false
    description: Head ref. Default is 'HEAD'.
  input-template:
    default: "v{version}"
    required: false
    description: Template used to detect the version
  output-template:
    default: "v{version}"
    required: false
    description: Template used to write next version out
  major-types:
    default: ""
    required: false
    description: |
      Define types which increment major number. By default, all types which ends with '!'
      or commits containing 'BREAKING CHANGE' or 'BREAKING-CHANGE' in commit message body 
      define a breaking change. Types added here will extend the default behavior.
  minor-types:
    default: ""
    required: false
    description: |
      Define types which increment minor number. Default is 'feat'.
      Types can be comma separated (no space). Provided types overwrite the default.
  patch-types:
    default: ""
    required: false
    description: |
      Define types which increment patch number. Default is 'fix'.
      Types can be comma separated (no space). Provided types overwrite the default.
  vars:
    default: ""
    required: false
    description: |
      Pass extra variables to be used in output template (ex.: build=b1,info=something)
  working-directory:
    default: "."
    required: false
    description: Package location - used to detect changes within that directory (and its children)

outputs:
  output:
    description: Next version output
    value: ${{ steps.next-version.outputs.output }}

runs:
  using: composite
  steps:
    - name: Install NexVer
      env:
        NEXVER_VERSION: "1.2.3"
      shell: bash
      run: ${{ github.action_path }}/scripts/nexver-install

    - name: Run detection
      id: next-version
      env:
        NEXVER_VERSION: "1.2.3"
        BASE_REF: ${{ inputs.base-ref }}
        HEAD_REF: ${{ inputs.head-ref }}
        INPUT_TEMPLATE: ${{ inputs.input-template }}
        MAJOR_TYPES: ${{ inputs.major-types }}
        MINOR_TYPES: ${{ inputs.minor-types }}
        OUTPUT_TEMPLATE: ${{ inputs.output-template }}
        PATCH_TYPES: ${{ inputs.patch-types }}
        VARS: ${{ inputs.vars }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
      shell: bash
      run: ${{ github.action_path }}/scripts/run-detection
