#!/usr/bin/env sh

set -eu

: "${GITHUB_OUTPUT:?not defined}"


binary="nexver"
version="${NEXVER_VERSION:-1.0.0}"

arch="$(uname -m)"
binary_path="${HOME}/.local/bin"
if [ "${RUNNER_TOOL_CACHE:-}" != "" ]; then
    binary_path="${RUNNER_TOOL_CACHE}/nexver/${version}/${arch}"
fi

if [ "${PATH##"${binary_path}"}" = "${PATH}" ]; then
    export PATH="${binary_path}:${PATH}"
fi

if command -v "${binary}" > /dev/null 2>&1; then
    current_version="$(${binary} --version | cut -d' ' -f2 -)"
    if [ "${current_version}" != "${version}" ]; then
        export PATH="${binary_path}:${PATH}"
    fi
else
    echo "nexver binary not found. Please install it first!"
    exit 1
fi

call_nexver() {
    test "${BASE_REF:-}" != "" && set -- --base-ref "${BASE_REF}" "$@"
    test "${HEAD_REF:-}" != "" && set -- --head-ref "${HEAD_REF}" "$@"
    test "${MAJOR_TYPES:-}" != "" && set -- --major-types "${MAJOR_TYPES}" "$@"
    test "${MINOR_TYPES:-}" != "" && set -- --minor-types "${MINOR_TYPES}" "$@"
    test "${PATCH_TYPES:-}" != "" && set -- --patch-types "${PATCH_TYPES}" "$@"
    test "${VARS:-}" != "" &&  for entry in $(echo "${VARS}" | tr ',' "\n"); do set -- --set "${entry}" "$@"; done
    test "${INPUT_TEMPLATE:-}" != "" && set -- --input-template "${INPUT_TEMPLATE}" "$@"
    test "${OUTPUT_TEMPLATE:-}" != "" && set -- --output-template "${OUTPUT_TEMPLATE}" "$@"

    "${binary}" "$@"
}

output="$(call_nexver "${WORKING_DIRECTORY:-.}")"

echo "output=$output" >>"${GITHUB_OUTPUT}"
